EsyaCart/Models/Vendor/AddProductModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace EsyaCart.Models.Vendor
{
    public class AddProductModel
    {
        [Required]
        public int Category_Id { get; set; }

        [Required(ErrorMessage = "ProductName is Required")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Price is Required")]
        public float Price { get; set; }

        [Required(ErrorMessage = "Quantity is Required")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Description is Required")]
        [StringLength(maximumLength: 200)]
        public string Descirption { get; set; }

        [Required, DataType(DataType.Upload)]
        public IFormFile ImageUrl { get; set; }

    }
}

EsyaCart/Pages/Vendor/AddProduct.cshtml.cs
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.Vendor;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EsyaCart.Pages.Vendor
{
    public class AddProduct : PageModel
    {

        public bool approval;
        public int sellerId; // vendorID in Db context
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public AddProduct(AppDbContext context, IWebHostEnvironment _env)
        {
            _context = context;
            _environment = _env;
        }

        [BindProperty]
        public AddProductModel addProductModel { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var sessionData = HttpContext.Session.GetString("VendorSessionId");

            if(sessionData != null)
            {
                int vendorSessionId = Convert.ToInt32(sessionData);
                var vendorData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
                approval = vendorData.IsApproved;
                sellerId = vendorData.VendorID;

                ViewData["CategoryList"] = await _context.Catagory
                    .Select(c => new SelectListItem
                    {
                        Value = c.Catagory_Id.ToString(),
                        Text = c.CatagoryName.ToString()
                    }).ToListAsync();

                return Page();
            }
            else
            {
                TempData["ToastMessage"] = "Please Login!";
                TempData["ToastType"] = "warning";
                return RedirectToPage("/Vendor/VendorLogin");
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            int vendorSessionId = Convert.ToInt32(HttpContext.Session.GetString("VendorSessionId"));
            var vendorData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
            approval = vendorData.IsApproved;
            sellerId = vendorData.VendorID;

            ViewData["CategoryList"] = await _context.Catagory
            .Select(c => new SelectListItem
            {
               Value = c.Catagory_Id.ToString(),
               Text = c.CatagoryName
            }).ToListAsync();

            if (ModelState.IsValid)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(addProductModel.ImageUrl.FileName);

                string filePath = Path.Combine(_environment.WebRootPath, "Uploads", fileName);

                var fileStream = new FileStream(filePath, FileMode.Create);

                await addProductModel.ImageUrl.CopyToAsync(fileStream);

                var selectedCategoryId = addProductModel.Category_Id;

                Products product = new Products
                {  
                    Category_Id = selectedCategoryId,
                    Vendor_Id = sellerId,
                    ProductName = addProductModel.ProductName,
                    Price = addProductModel.Price,
                    Quantity = addProductModel.Quantity,
                    Description = addProductModel.Descirption,
                    IsActive = false,
                    ImageUrl = fileName
                };

                await _context.Products.AddAsync(product);
                await _context.SaveChangesAsync();

                TempData["ToastMessage"] = "New Product Added";
                TempData["ToastType"] = "success";

                return RedirectToPage("/Vendor/ViewProducts");
                
            }
            else
            {
                TempData["ToastMessage"] = "Please, Fill all the feilds";
                TempData["ToastType"] = "warning";
                return RedirectToPage();
            }
        }
    }
}

EsyaCart/Pages/Vendor/EditProduct.cshtml.cs
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.Vendor;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EsyaCart.Pages.Vendor
{
    public class EditProduct : PageModel
    {
        private readonly AppDbContext _context;

        public EditProduct(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Products products { get; set; }

        [BindProperty]
        public EditProductModel editProducts { get; set; }


        public async Task<IActionResult> OnGetAsync(int productId)
        {
            var sessionData = HttpContext.Session.GetString("VendorSessionId");
            if(sessionData != null)
            {
                var OldData = await _context.Products.FindAsync(productId);
                if (OldData != null)
                {
                    editProducts = new EditProductModel
                    {
                        ProductName = OldData.ProductName,
                        Price = OldData.Price,
                        Quantity = OldData.Quantity,
                        Description = OldData.Description
                    };
                }
                return Page();
            }
            else
            {
                return RedirectToPage("/Vendor/VendorLogin");
            }
                
        }

        public IActionResult OnPost(int productId)
        {
            var UpdatedData = _context.Products.Find(productId);
            if (UpdatedData != null)
            {
                UpdatedData.ProductName = editProducts.ProductName;
                UpdatedData.Price = editProducts.Price;
                UpdatedData.Quantity = editProducts.Quantity;
                UpdatedData.Description = editProducts.Description;
                UpdatedData.updatedAt = DateTime.Now;

                _context.SaveChanges();

                TempData["ToastMessage"] = "Product saved successfully!";
                TempData["ToastType"] = "success";

                return RedirectToPage("/Vendor/ViewProducts");
            }
            
            return Page();
        }
    }
}

EsyaCart/Pages/Vendor/SessionClearer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EsyaCart.Pages.Vendor
{
    public class SessionClearerModel : PageModel
    {
        public IActionResult OnGetSessionClearer()
        {
            HttpContext.Session.Clear();
            return new JsonResult(new { success = true });
        }
    }
}

EsyaCart/Pages/Vendor/VendorHome.cshtml.cs
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.Vendor;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EsyaCart.Pages.Vendor
{
	public class VendorHome : PageModel
    {
		public bool approval;


		private readonly AppDbContext _context;

        public VendorHome(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public VendorDetailsModel vendorDetailsModel { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
			var sessionData = HttpContext.Session.GetString("VendorSessionId");
			if(sessionData != null)
			{
                int vendorSessionId = Convert.ToInt32(sessionData);
                var vendorData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
                approval = vendorData.IsApproved;
                return Page();
            }
			else
			{
				return RedirectToPage("/Vendor/VendorLogin");
			}
				
		}

        public async Task<IActionResult> OnPostAsync() {

            int vendorSessionId = Convert.ToInt32(HttpContext.Session.GetString("VendorSessionId"));

            var UpdatedData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
			// 9 = Session Id
			if (UpdatedData != null)
			{
				UpdatedData.VendorName = vendorDetailsModel.VendorName;
				UpdatedData.Area= vendorDetailsModel.Area;
				UpdatedData.Landmark = vendorDetailsModel.Landmark;
				UpdatedData.Pincode = vendorDetailsModel.Pincode;
				UpdatedData.IsApproved = vendorDetailsModel.isApproved;

				_context.SaveChanges();

				TempData["Success"] = "Details Updated Successfully";

				return RedirectToPage();
			}
			else
			{
				return Page();
			}
		}
    }
}

EsyaCart/Pages/Vendor/VendorLogin.cshtml.cs
using EsyaCart.Data.Context;
using EsyaCart.Models.Vendor;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EsyaCart.Pages.Vendor
{
    public class VedorLogin : PageModel
    {
        private readonly AppDbContext _context;
        public VedorLogin(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public VendorLoginModel vendorLoginModel { get; set; }

        public IActionResult OnGet()
        {  
            var sessionData = HttpContext.Session.GetString("VendorSessionId");
            if (sessionData != null) {
                return RedirectToPage("/Vendor/VendorHome");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var validUser = await _context.Account
                    .SingleOrDefaultAsync(x => x.Email == vendorLoginModel.Email && x.Password == vendorLoginModel.Password);

                if (validUser != null)
                {
                    TempData["Success"] = "User " + validUser.Email + " Logedin SUccessfull";
                    Console.WriteLine(TempData["Success"]);

                    var accountId = validUser.Account_Id;
                    
                    HttpContext.Session.SetString("VendorSessionId", accountId.ToString());

                    TempData["ToastMessage"] = "Login Successfull!";
                    TempData["ToastType"] = "success";

                    return RedirectToPage("/Vendor/ViewAnalytics");
                }
                else
                {
                    ModelState.AddModelError("vendorLoginModel.Password", "Invalid credentials");
                }
            }
            return Page();
        }

    }
}

EsyaCart/Pages/Vendor/ViewProducts.cshtml.cs
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Numerics;


namespace EsyaCart.Pages.Vendor
{
    public class ViewProducts : PageModel
    {

        public bool approval;
        public int sellerId;
        private readonly AppDbContext _context;

        public ViewProducts(AppDbContext context)
        {
            _context = context;
        }

        public List<Catagory> categoryList { get; set; } = new List<Catagory>();

        public List<ProductReviews> productReviews { get; set; } = new List<ProductReviews>();
		public async Task<IActionResult> OnGetAsync()
        {
            var sessionData = HttpContext.Session.GetString("VendorSessionId");
            if(sessionData != null)
            {
                int vendorSessionId = Convert.ToInt32(sessionData);
                var vendorData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
                approval = vendorData.IsApproved;
                sellerId = vendorData.VendorID;

                productReviews = (from product in _context.Products
                                  join review in _context.Reviews
                                  on product.Product_Id equals review.Product_Id into reviewGroup
                                  where (product.Vendor_Id == sellerId)
                                  select new ProductReviews
                                  {
                                      Vendor_Id = product.Vendor_Id,
                                      Product_Id = product.Product_Id,
                                      ProductName = product.ProductName,
                                      Price = product.Price,
                                      Quantity = product.Quantity,
                                      IsActive = product.IsActive,
                                      Description = product.Description,
                                      ImageUrl = product.ImageUrl,
                                      Ratings = reviewGroup.Any() ? reviewGroup.Average(r => r.Ratings) : 0  
                                  }).ToList();

                categoryList = await _context.Catagory.ToListAsync();
                return Page();
            }
            else
            {
                return RedirectToPage("/Vendor/VendorLogin");
            }
        }

        public async Task<IActionResult> OnPostCategoryAsync(int categoryId)
        {

            int vendorSessionId = Convert.ToInt32(HttpContext.Session.GetString("VendorSessionId"));

            var vendorData = _context.VendorDetails.Where(p => p.Accounts_Id == vendorSessionId).FirstOrDefault();
            approval = vendorData.IsApproved;
            sellerId = vendorData.VendorID;

            if (categoryId == 0)
            {
                return Page();
            }
            else
            {
                categoryList = await _context.Catagory.ToListAsync();

                productReviews = (from product in _context.Products
                                      join review in _context.Reviews
                                      on product.Product_Id equals review.Product_Id into reviewGroup
                                      where (product.Category_Id == categoryId && product.Vendor_Id == sellerId)
                                      select new ProductReviews
                                      {
                                          Vendor_Id = product.Vendor_Id,
                                          Product_Id = product.Product_Id,
                                          ProductName = product.ProductName,
                                          Price = product.Price,
                                          Quantity = product.Quantity,
                                          IsActive = product.IsActive,
                                          Description = product.Description,
                                          ImageUrl = product.ImageUrl,
                                          Ratings = reviewGroup.Any() ? reviewGroup.Average(r => r.Ratings) : 0  // Average rating if there are reviews
                                      }).ToList();



                if (productReviews.Count == 0)
                {
					productReviews.Clear();
                }

                return Page();
            }
        }

        public async Task<IActionResult> OnPostEnableAsync(int productId)
        {
            var currentProduct = await _context.Products.FindAsync(productId);
            if (currentProduct != null)
            {
                currentProduct.IsActive = true;
                await _context.SaveChangesAsync();
                TempData["ToastMessage"] = "Product is live now!";
                TempData["ToastType"] = "info";
                return RedirectToPage();
            }
            else
            {
                TempData["ToastMessage"] ="Error while fetching product data";
                TempData["ToastType"] = "error";
                return Page();
            }
        }

        public async Task<IActionResult> OnPostDisableAsync(int productId)
        {
            var currentProduct = await _context.Products.FindAsync(productId);
            if(currentProduct != null && currentProduct.IsActive == true)
            {
                currentProduct.IsActive = false;
                await _context.SaveChangesAsync();

                TempData["ToastMessage"] = "Product Disabled for selling!";
                TempData["ToastType"] = "warning";
                return RedirectToPage();
            }
            else
            {
                return Page();
            }
        }
    }

    public class ProductReviews
    {

        public int Vendor_Id { get; set; }
        public int Product_Id { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }

        public bool IsActive { get; set; }

        public int Quantity { get; set; }

        public double Price { get; set; }

        public string ImageUrl { get; set; }

        public float Ratings { get; set; }
    }
}

EsyaCart/Pages/Vendor/AddProduct.cshtml
@page
@model EsyaCart.Pages.Vendor.AddProduct
@{
}

@{
    if(Model.approval == true)
    {
        <section class="m-0 p-0 mx-5">
            <div class="card mx-5 addProduct__card">
                <div class="container">
                    <div class="row d-flex align-items-center justify-content-center">
                        <div class="col-12 col-md-6">
                            <div class="p-md-4 py-5">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="mb-2">
                                            <h2 class="h3">Add New Product</h2>
                                        </div>
                                    </div>
                                </div>
                                <form method="post" enctype="multipart/form-data">
                                    <div class="row gy-1 gy-md-2 overflow-hidden">
                                        <div class="col-12">
                                            <label asp-for="addProductModel.ProductName" class="form-label">Product Name</label>
                                            <input type="text" asp-for="addProductModel.ProductName" class="form-control" />
                                            <span asp-validation-for="addProductModel.ProductName" class="text-danger"></span>
                                        </div>
                                        <div class="row">
                                            <div class="col-6">

                                                <label asp-for="addProductModel.Price" class="form-label">Price</label>
                                                <input type="number" asp-for="addProductModel.Price" class="form-control" />
                                                <span asp-validation-for="addProductModel.ProductName" class="text-danger"></span>
                                            </div>
                                            <div class="col-6">
                                                <label asp-for="addProductModel.Quantity" class="form-label">Quantity</label>
                                                <input type="text" asp-for="addProductModel.Quantity" class="form-control" />
                                                <span asp-validation-for="addProductModel.Quantity" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <label asp-for="addProductModel.Descirption" class="form-label">Description</label>
                                            <input type="text-area" asp-for="addProductModel.Descirption" class="form-control" />
                                            <span asp-validation-for="addProductModel.Descirption" class="text-danger"></span>
                                        </div>
                                        <div class="col-12">
                                            <label asp-for="addProductModel.Category_Id" class="form-label">Category</label>
                                            <select asp-for="addProductModel.Category_Id" class="form-control">
                                                <option value="">Select a category</option>
                                                @foreach (var category in (List<SelectListItem>)ViewData["CategoryList"])
                                                {
                                                    <option value="@category.Value">@category.Text</option>
                                                }
                                            </select>
                                        </div>
                                        <div class="col-12">
                                            <label asp-for="addProductModel.ImageUrl" class="form-label">Upload Image</label>
                                            <input asp-for="addProductModel.ImageUrl" class="form-control" />
                                        </div>

                                        <div class="col-12">
                                            <div class="d-grid">
                                                <button class="btn bsb-btn-xl signup__btn" type="submit">Add</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }
    else
    {
        <div class="mt-5 d-flex align-items-center justify-content-center">
            <div>
                <img src="~/Images/Seller/approval-waiting.jpg" style="height: 450px; width: 400px;">
                <h3 class="text-center">Waiting for Approval</h3>
                <p class="text-center">you can sell the products once you are approved</p>
            </div>
        </div>
    }
}

EsyaCart/Pages/Vendor/SessionClearer.cshtml
@page
@model EsyaCart.Pages.Vendor.SessionClearerModel
@{
}

EsyaCart/Pages/Vendor/ViewOrders.cshtml
@page
@model EsyaCart.Pages.Vendor.ViewOrders
@{
}

@{
	Console.WriteLine("This page is called");
}

		@{
			if(Model.sellerOrders.Count != 0)
			{
				<table class="table">
					<thead>
					<th>Product Name</th>
					<th>No.of Items Sold</th>
					</thead>
					<tbody>
						@{foreach (var orderList in Model.sellerOrders)
							{
								<tr>
									<td>@orderList.ProductName</td>
									@{
										if(@orderList.OrdersCount == 0){
										<td>No orders placed yet</td>
									}
									else{
										<td>@orderList.OrdersCount</td>
									}
									}
									
								</tr>
							}
						}
					</tbody>
				</table>
			}
			else
			{
				<h1>No Oreders Placed for your porducts</h1>
			}
			
		}

EsyaCart/Pages/Vendor/ViewProducts.cshtml
@page
@model EsyaCart.Pages.Vendor.ViewProducts
@{
    // style="box-shadow: rgba(0, 0, 0, 0.15) 0px 15px 25px, rgba(0, 0, 0, 0.05) 0px 5px 10px;"
}
@{
    if (Model.approval == true)
    {
        <div class="border border-light rounded-2 py-2 mx-5 d-flex g-5">
        @foreach (var category in Model.categoryList)
        {
            <form asp-page-handler="Category" asp-route-categoryId="@category.Catagory_Id">
                <button class="btn btn-outline-dark mx-3" type="submit">@category.CatagoryName</button>
            </form>
        }
    </div>

    <div class="row g-2 mx-5 mt-3">
         @{
                if (Model.productReviews.Count != 0)
                {
                    foreach (var product in Model.productReviews)
                    {
                        <div class="col-12">
                            <div class="card border-0 p-4 rounded-3 product__card">
                               
                                <div class="row align-items-center">
                                    <aside class="col-md-2">
                                        <a href="#">
                                            <img src="~/Uploads/@product.ImageUrl" alt="product-image" style="height : 144px; width : 157px;" />
                                        </a>
                                    </aside>
                                    <div class="col-md-6">
                                        <div class="info-main">
                                            <h2 class="h5 product__title">@product.ProductName</h2>
                                            <div class="d-flex my-3">
                                                @{
                                                    int num = Convert.ToInt32(product.Ratings);
                                                    if(num == 0)
                                                    {
                                                        for(int i = 0; i < 5; i++){
                                                            <i class="fa-regular fa-star text-warning mr-1"></i>
                                                        }
                                                        <span class="text-sm">No Ratings</span>
                                                    }
                                                    else
                                                    {
                                                        for (int i = 0; i < num; i++)
                                                        {
                                                            <i class="star fas fa-star text-warning mr-1"></i>
                                                        }
                                                        for(int i = 0; i < 5 - num; i++){
                                                            <i class="fa-regular fa-star text-warning"></i>
                                                        }
                                                    }
                                                    
                                                }


                                                <span class="badge text-dark ml-2">@num</span>

                                            </div>
                                            <p>@product.Description</p>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="d-flex align-items-center mb-2">
                                            <span class="h6 mb-0" style="font-size: 1.5rem; font-weight: 500;">₹ @product.Price</span>
                                        </div>
                                        <span class="text-success small"><i class="fas fa-shipping-fast mx-2"></i>Free shipping</span>
                                        <div class="d-flex g-4 mt-4">
                                            @{

                                                if (product.IsActive == true)
                                                {
                                                    <form method="post" class="mx-1">
                                                        <a asp-page="/Vendor/EditProduct" asp-route-productId="@product.Product_Id" class="btn mx-1 edit__btn">
                                                            <i class="fas fa-edit"></i>
                                                            Edit
                                                        </a>
                                                    </form>
                                                    <form asp-page-handler="Disable" asp-route-productId="@product.Product_Id" method="post" class="mx-1">
                                                        <button type="submit" class="btn edit__btn btn-sm btn-block text-light mx-3">
                                                            <i class="fa-regular fa-square-check"></i>
                                                            Disable
                                                        </button>
                                                    </form>
                                                }
                                                else
                                                {
                                                    <form method="post" class="mx-1" asp-route-productId="@product.Product_Id" asp-page-handler="Enable">
                                                        <button type="submit" class="btn btn-danger btn-sm btn-block text-light mx-3">
                                                            <i class="fa-regular fa-square-check"></i>
                                                            Enable
                                                        </button>
                                                    </form>
                                                }
                                            }
                                        </div>
                                    </div>
                                    <div class="col d-flex flex-column">
                                        <p class="text-lg-center">Quantity</p>
                                        <h3 class="fw-bolder text-xxl-center">@product.Quantity</h3>
                                        @{
                                            if (product.Quantity < 10)
                                            {
                                                <span class="text-danger">Only few items left</span>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="mt-5 d-flex align-items-center justify-content-center">
                        <div>
                            <img src="~/Images/Seller/not-found.jpg" style="height: 450px; width: 400px;">
                            <h3>Ooops..! No Products Found</h3>
                        </div>
                    </div>
                }
            }
        </div>

    }
    else
    {
        <div class="mt-5 d-flex align-items-center justify-content-center">
            <div>
                <img src="~/Images/Seller/approval-waiting.jpg" style="height: 450px; width: 400px;">
                <h3 class="text-center">Waiting for Approval</h3>
                <p class="text-center">you can sell the products once you are approved</p>
            </div>
        </div>
    }
}