EsyaCart/Models/User/CartModelClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EsyaCart.Models.User
{
    public class CartModelClass
    {
        public int Customer_Id { get; set; }            // Customer_Id = Account.Account_Id

        public int Product_Id { get; set; }

        public int Quantity { get; set; }
    }
}

EsyaCart/Pages/User/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class Dashboard : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<Dashboard> _logger;
        public List<Catagory> catagoryList {get;set;} = new List<Catagory>();
        public List<Products> productsEntity {get;set;} = new List<Products>();
        public Dashboard(ILogger<Dashboard> logger,AppDbContext dbContext)
        {
            _logger = logger;
            _context = dbContext;
        }
        public Cart cart { get; set; } = new Cart();
        public int customerid { get; set; }
        public string logoutchecksession {get;set;} = "";
        public async Task OnGet(string catagoryName)
        {
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                Console.WriteLine($"session id===>{logoutchecksession}");
                catagoryList = await _context.Catagory.ToListAsync();
                if(catagoryList.Count < 0)throw new Exception("catagory not there");
                if(catagoryName==null)
                productsEntity = await _context.Products.ToListAsync();
                else{
                    productsEntity = await (from prod in _context.Products
                                            join cat in _context.Catagory
                                            on prod.Category_Id equals cat.Catagory_Id
                                            where cat.CatagoryName == catagoryName
                                            select prod).ToListAsync();
                }
                if(productsEntity.Count<0)throw new Exception("Products not available");
            }
            catch (Exception e)
            {
               Console.WriteLine($"error=> {e.Message}");
            }
        }

        public async Task<IActionResult> OnPostAddCartAndBuy(int prodId){
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession == null)return RedirectToPage("../User/UserLogin");
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);

                if(cart!=null){
                    cart.Quantity = cart.Quantity + 1;
                    await _context.SaveChangesAsync();
                    return RedirectToPage("../User/UserCart");
                }

                var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();

                return RedirectToPage("../User/UserCart");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }
    }
}

EsyaCart/Pages/User/SearchBar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class SearchBar : PageModel
    {
        private readonly ILogger<SearchBar> _logger;

        public SearchBar(ILogger<SearchBar> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

EsyaCart/Pages/User/UserLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Models.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    
    public class UserLogin : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UserLogin> _logger;

        public UserLogin(ILogger<UserLogin> logger,AppDbContext dbContext)
        {
            _logger = logger;
            _context = dbContext;
        }

        [BindProperty]
        public LoginModelClass LInput { get; set; } = new LoginModelClass();
        public async Task<IActionResult> OnGet()
        {
            var UsersessionId = HttpContext.Session.GetString("UserSessionId");
            Console.WriteLine($"Usersession id===>{UsersessionId}");
            if(UsersessionId!=null)return RedirectToPage("../User/Dashboard");
            return Page();
        }

        public async Task<IActionResult> OnPost(){
             try
             {
                if (!ModelState.IsValid)
               {
                   throw new Exception("Invalid Details");
               }
               else
               {
                   var author=await _context.Account.Where(p=>p.Email==LInput.Email && p.Password==LInput.Password).FirstOrDefaultAsync();
                   if (author == null)
                   {
                       throw new Exception("Enter Correct Login Details");
                   }
                   HttpContext.Session.SetString("UserSessionId","UserSesseionValueSettinByJoydeep@1047893#hdfkjhfe");
                   HttpContext.Session.SetInt32("CustomerId",author.Account_Id);
                   return RedirectToPage("../User/Dashboard");
               }
             }
             catch (Exception e)
             {
                Console.WriteLine(e.Message);
                TempData["error"] = e.Message.ToString();
                return Page();
             }
        }
    }
}

EsyaCart/Pages/User/UserLogout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class UserLogout : PageModel
    {
        private readonly ILogger<UserLogout> _logger;

        public UserLogout(ILogger<UserLogout> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("../User/Dashboard");
        }
    }
}

EsyaCart/Pages/User/UserProfile/Edituserprofile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User.UserProfile
{
    public class Edituserprofile : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UsersProfile> _logger;

        public Edituserprofile(ILogger<UsersProfile> logger,AppDbContext dbcontext)
        {
            _logger = logger;
            _context = dbcontext;
        }

        public UserDetails userdetail {get; set;} = new UserDetails();
        public Account userAcc {get; set;} = new Account();
        [BindProperty]
        public UserDetailsModelClass udmc {get; set;} = new UserDetailsModelClass();
         public string logoutchecksession {get;set;} = "";
        public int customerid { get; set; }
        public async Task<IActionResult> OnGet(int id)
        {
           try
           {
                Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
                Response.Headers["Pragma"] = "no-cache";
                Response.Headers["Expires"] = "0";
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession==null || customerid==0 ||customerid==null)return RedirectToPage("../../User/UserLogin");

             userdetail = await _context.UserDetails.FirstOrDefaultAsync(u=>u.Accounts_Id==id);
             userAcc = await _context.Account.FirstOrDefaultAsync(u=>u.Account_Id==id);

             if(userdetail==null && userAcc==null)throw new Exception("User Details not found");
             return Page();
           }
           catch (Exception e)
           {
                Console.WriteLine(e.Message);
                TempData["msg"] = "Data not found";
                return Page();
           }

        }
        public async Task<IActionResult> OnPostEdit(int id){
            try
            {
                userdetail = await _context.UserDetails.FirstOrDefaultAsync(i=>i.Accounts_Id==id);
                if(userdetail!=null){
                    userdetail.UserName = udmc.UserName;
                    userdetail.Area = udmc.Area;
                    userdetail.Landmark = udmc.Landmark;
                    userdetail.Pincode = udmc.Pincode;
                    await _context.SaveChangesAsync();
                    return RedirectToPage("../UserProfile/UsersProfile");
                }
                var usrdet = new UserDetails{
                    Accounts_Id = id,
                    UserName = udmc.UserName,
                    Area = udmc.Area,
                    Landmark = udmc.Landmark,
                    Pincode = udmc.Pincode,
                };
                await _context.UserDetails.AddAsync(usrdet);
                await _context.SaveChangesAsync();
                return RedirectToPage("../UserProfile/UsersProfile");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }
    }
}

EsyaCart/Pages/User/UserProfile/UserOrderShow.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User.UserProfile
{
    public class UserOrderShow : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UserOrderShow> _logger;
        public List<UserOrdersDetails> orderdet {get; set;} = new List<UserOrdersDetails>();
        public Reviews review {get;set;} =new Reviews();
        [BindProperty]
        public ReviewModelClass reviewmodel {get; set;} = new ReviewModelClass();
        public UserOrderShow(ILogger<UserOrderShow> logger,AppDbContext Dbcontext)
        {
            _logger = logger;
            _context = Dbcontext;
        }
         public string logoutchecksession {get;set;} = "";
        public int customerid { get; set; } 
        public async Task<IActionResult> OnGet()
        {
           try
           {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession==null || customerid==0 ||customerid==null)return RedirectToPage("../../User/UserLogin");

             orderdet = await(from order in _context.Orders
             join ordItems in _context.OrderItems
             on order.Order_id equals ordItems.Order_Id
             join prod in _context.Products
             on ordItems.Product_Id equals prod.Product_Id
             where order.Customer_Id==customerid
             select new UserOrdersDetails{
                Product_id = prod.Product_Id,
                 ProdQuantity = ordItems.Quantity,
                 TotPrice = order.TotalPrice,
                 DeliveryStatus = order.isDelivered,
                 prodimgUrl = prod.ImageUrl,
                 ProdName = prod.ProductName,
                 orderdate = order.OrderedDate.ToLocalTime()
             }).ToListAsync();
             if(orderdet.Count<0)throw new Exception("Order is empty");

             return Page();
           }
           catch (Exception e)
           {
            Console.WriteLine(e.Message);
            TempData["err"] = "Didnot Order Anything";
            return Page();
           }
        }
        
        public async Task<IActionResult> OnPostEditReviews(int prodid){
            try
            {
                Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
                Response.Headers["Pragma"] = "no-cache";
                Response.Headers["Expires"] = "0";
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                Console.WriteLine($"productid is====>{prodid}");
                review = await _context.Reviews.FirstOrDefaultAsync(p=>p.Product_Id==prodid && p.Customer_Id==customerid);
                if(review==null){
                    if(!ModelState.IsValid)
                    {
                        throw new Exception("Error in data fetching from reviews input");
                    }
                    var rev = new Reviews{
                        Ratings = reviewmodel.Ratings,
                        Description = reviewmodel.Description,
                        Customer_Id = customerid,
                        Product_Id = prodid
                    };
                    await _context.Reviews.AddAsync(rev);
                    await _context.SaveChangesAsync();
                    return RedirectToPage("../../User/Productanddetails", new {productID = prodid});
                }

                review.Description = reviewmodel.Description;
                review.Ratings = reviewmodel.Ratings;
                await _context.SaveChangesAsync();
                return RedirectToPage("../../User/Productanddetails", new {productID = prodid});
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToPage("../UserProfile/UsersProfile");
            }
        }
        
    }
    public class UserOrdersDetails{
        public int Product_id { get; set; }
        public int ProdQuantity {get;set;}
        public double TotPrice {get;set;}
        public bool DeliveryStatus {get;set;}
        public string prodimgUrl {get;set;}
        public string ProdName{get;set;}
        public DateTime orderdate {get;set;}
    }
}

EsyaCart/Pages/User/UserProfile/UsersProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User.UserProfile
{
    
    public class UsersProfile : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UsersProfile> _logger;

        public UsersProfile(ILogger<UsersProfile> logger,AppDbContext dbcontext)
        {
            _logger = logger;
            _context = dbcontext;
        }

        public UserDetails userdetail {get; set;} = new UserDetails();
        public Account userAcc {get; set;} = new Account();
        public UserDetailsModelClass udmc {get; set;} = new UserDetailsModelClass();
        public int c_id {get;set;} = 0;
         public string logoutchecksession {get;set;} = "";
        public int customerid { get; set; } 
        public async Task<IActionResult> OnGet()
        {
           try
           {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "0";
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession==null || customerid==0 ||customerid==null)return RedirectToPage("../../User/UserLogin");
             c_id = customerid;
             userdetail = await _context.UserDetails.FirstOrDefaultAsync(u=>u.Accounts_Id==c_id);
             userAcc = await _context.Account.FirstOrDefaultAsync(u=>u.Account_Id==c_id);

             if(userdetail==null && userAcc==null)throw new Exception("User Details not found");
             udmc.UserName = userdetail.UserName;
             udmc.Area = userdetail.Area;
             udmc.Landmark = userdetail.Landmark;
             udmc.Pincode = userdetail.Pincode;
             return Page();
           }
           catch (Exception e)
           {
                Console.WriteLine(e.Message);
                TempData["msg"] = "Data not found";
                return Page();
           }

        }

    }
}

EsyaCart/Pages/User/UserProfile/Edituserprofile.cshtml
@page
@model EsyaCart.Pages.User.UserProfile.Edituserprofile
@{
    ViewData["Title"] = "Edituserprofile";
}


<div class="setdivedit d-flex flex-column align-items-center justify-content-center">
    <form method="post" class="">
        <div class="d-flex align-items-center">
            Email:<span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc?.Email) ? "2rem" : "0.5rem");">
             @Model.userAcc?.Email
            </span>
            Contact:<span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc?.Contact_No) ? "2rem" : "0.5rem");">
                @Model.userAcc?.Contact_No
            </span>
        </div>
        <div class="d-flex align-items-center my-5 me-5">
            <label asp-for="@Model.udmc.UserName"></label>
            <input asp-for="@Model.udmc.UserName" class="form-control me-5" value="@Model.udmc.UserName"/>
            <span asp-validation-for="@Model.udmc.UserName" class="text-danger"></span>
            <label asp-for="@Model.udmc.Pincode" class=""></label>
            <input asp-for="@Model.udmc.Pincode" class="form-control" value="@Model.udmc.Pincode"/>
            <span asp-validation-for="@Model.udmc.Pincode" class="text-danger"></span>
        </div>
        <div class="d-flex align-items-center me-5">
           <label asp-for="@Model.udmc.Landmark"></label>
            <input asp-for="@Model.udmc.Landmark" class="form-control me-5" value="@Model.udmc.Landmark"/>
            <span asp-validation-for="@Model.udmc.Landmark" class="text-danger"></span>
            <label asp-for="@Model.udmc.Area" class=""></label>
            <input asp-for="@Model.udmc.Area" class="form-control" value="@Model.udmc.Area"/>
            <span asp-validation-for="@Model.udmc.Area" class="text-danger"></span>
        </div>
        <div class="d-flex align-items-center justify-content-center mt-5">
            <button asp-page-handler="Edit" asp-route-id="@Model.userAcc.Account_Id" class="btn btn-primary px-5 py-2 fs-4">Save</button>
        </div>
    </form>
</div>

EsyaCart/Pages/User/UserProfile/UserOrderShow.cshtml
@page
@model EsyaCart.Pages.User.UserProfile.UserOrderShow
@{
    ViewData["Title"] = "UserOrderShow";
}


<div class="container">
    <h2 class="text-center mt-3" style="color: rgb(129, 129, 129);">All Orders</h2>
    @if(Model.orderdet.Count>0){
        foreach(var ord in Model.orderdet)
        {
                    
            <div class="row settingborder mt-5">
                <a asp-page="../../User/Productanddetails" asp-route-productID = "@ord.Product_id" class="col d-flex align-items-center justify-content-center setimginorder">
                    <img src="~/Uploads/@ord.prodimgUrl" alt="Product Image" class="orderimg">
                </a>
                <div class="col">
                    <div class=" d-flex flex-column">
                        <a asp-page="../../User/Productanddetails" asp-route-productID = "@ord.Product_id" class="fs-4 text-decoration-none text-dark">@ord.ProdName</a>
                        <div class="">
                            <span class="fs-6">Order Date : </span><span class="fs-6 text-success">@ord.orderdate</span>
                        </div>
                        <div class="">
                            <span class="fs-6">Total quantity : </span><span class="fs-6 text-success">@ord.ProdQuantity</span>
                        </div>
                        @if(ord.DeliveryStatus==true){
                            <p class="fs-5 mt-2 text-success">Delivered</p>
                        }else{
                            <p class="fs-5 mt-2 text-warning">Not Delivered</p>
                        }
                        
                    </div>
                </div>
                <div class="col">
                <div class="d-flex flex-column align-items-center">
                        <div class="">
                            <span class=" fs-4 mx-2">₹ </span><span class=" fs-4 text-success">@ord.TotPrice</span>
                        </div>
                        <div>
                            <button  class="btn btn-secondary mt-3 ms-5" data-bs-toggle="modal" data-bs-target="#cartModal-@ord.Product_id">Add Reviews</button>
                        </div>
                        @if(ord.DeliveryStatus==true){
                            <button class="btn btn-danger mt-4 ms-5">Cancel order</button>
                        }
                        
                </div>
                </div>
            </div>
            <div class="modal fade" id="cartModal-@ord.Product_id" tabindex="-1" aria-labelledby="cartModalLabel-@ord.Product_id" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cartModalLabel-@ord.Product_id">Add Product review</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex">
                <div class="d-flex align-items-center justify-content-center setimginorder">
                    <img src="~/Uploads/@ord.prodimgUrl" alt="Product Image" class="orderimg2">
                </div>
                <div class="">
                    <form method="post" asp-page-handler="EditReviews" asp-route-prodid="@ord.Product_id">
                        <textarea asp-for="@Model.reviewmodel.Description" class="form-control ms-3" style="resize: none;" cols="30" rows="3" placeholder="Write Review..."></textarea>
                        <input type="number" asp-for="@Model.reviewmodel.Ratings" step="0.1" class="form-control ms-3 mt-2" placeholder="Rating.. 0-5" min="0" max="5" required>
                        <span asp-validation-for="@Model.reviewmodel.Ratings"></span>
                       
                        
                        <button type="submit" class="btn btn-secondary mt-3" data-bs-dismiss="modal">Submit Review</button>
                        
                    </form>

                    </div>
                </div>
            </div>
            </div>
            </div>
        }
    }else{
        
    }
</div>

EsyaCart/Pages/User/UserProfile/UsersProfile.cshtml
@page
@model EsyaCart.Pages.User.UserProfile.UsersProfile
@{
    ViewData["Title"] = "UsersProfile";
}

<div class="btn btn-primary mt-3">
    <a class="text-decoration-none text-white" asp-page="../UserProfile/Edituserprofile" asp-route-id="@Model.c_id">Edit Profile</a>
</div>

<div class="d-flex flex-column align-items-center justify-content-center">
    @if (Model.userdetail != null && Model.userAcc != null)
    {
        <div class="d-flex align-items-center">
            <span class="btn m-3 sp1" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userdetail.UserName) ? "2rem" : "1.5rem");">
                @Model.userdetail.UserName
            </span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc.Email) ? "2rem" : "1.5rem");">
                @Model.userAcc.Email
            </span>
        </div>
        <div class="d-flex align-items-center">
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc.Contact_No) ? "2rem" : "1.5rem");">
                @Model.userAcc.Contact_No
            </span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userdetail.Pincode.ToString()) ? "2rem" : "1.5rem");">
                @Model.userdetail.Pincode
            </span>
        </div>
        <div class="d-flex align-items-center">
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userdetail.Area) ? "2rem" : "1.5rem");">
                @Model.userdetail.Area
            </span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userdetail.Landmark) ? "2rem" : "1.5rem");">
                @Model.userdetail.Landmark
            </span>
        </div>
    }
    else
    {
        <div class="d-flex align-items-center">
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc?.Email) ? "2rem" : "1.5rem");">
                @Model.userAcc?.Email
            </span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: @(string.IsNullOrEmpty(Model.userAcc?.Contact_No) ? "2rem" : "1.5rem");">
                @Model.userAcc?.Contact_No
            </span>
        </div>
        <div class="d-flex align-items-center">
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding:2rem;"></span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding:2rem;"></span>
        </div>
        <div class="d-flex align-items-center">
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: 2rem;"></span>
            <span class="btn m-3" style="background-color: #e6e6e6; min-width: 20rem; padding: 2rem;"></span>
        </div>
    }
</div>
<script src="~/js/User.js" asp-append-version="true"></script>