EsyaCart/Pages/User/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class Dashboard : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<Dashboard> _logger;
        public List<Catagory> catagoryList {get;set;} = new List<Catagory>();
        public List<Products> productsEntity {get;set;} = new List<Products>();
        public Dashboard(ILogger<Dashboard> logger,AppDbContext dbContext)
        {
            _logger = logger;
            _context = dbContext;
        }
        public Cart cart { get; set; } = new Cart();
        public int customerid { get; set; }
        public string logoutchecksession {get;set;} = "";
        public async Task OnGet(string catagoryName)
        {
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                Console.WriteLine($"session id===>{logoutchecksession}");
                catagoryList = await _context.Catagory.ToListAsync();
                if(catagoryList.Count < 0)throw new Exception("catagory not there");
                if(catagoryName==null)
                productsEntity = await _context.Products.ToListAsync();
                else{
                    productsEntity = await (from prod in _context.Products
                                            join cat in _context.Catagory
                                            on prod.Category_Id equals cat.Catagory_Id
                                            where cat.CatagoryName == catagoryName
                                            select prod).ToListAsync();
                }
                if(productsEntity.Count<0)throw new Exception("Products not available");
            }
            catch (Exception e)
            {
               Console.WriteLine($"error=> {e.Message}");
            }
        }

        public async Task<IActionResult> OnPostAddCartAndBuy(int prodId){
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession == null)return RedirectToPage("../User/UserLogin");
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);

                if(cart!=null){
                    cart.Quantity = cart.Quantity + 1;
                    await _context.SaveChangesAsync();
                    return RedirectToPage("../User/UserCart");
                }

                var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();

                return RedirectToPage("../User/UserCart");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }
    }
}

EsyaCart/Pages/User/Productanddetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using EsyaCart.Models.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class Productanddetails : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<Productanddetails> _logger;

        public Productanddetails(ILogger<Productanddetails> logger,AppDbContext Dbcontext)
        {
            _logger = logger;
            _context = Dbcontext;
        }

        
        public Products ProductInfo { get; set; } = new Products();
        public List<UserReviewDetails> ProductReviewDetails { get; set; } = new List<UserReviewDetails>();

        public CartModelClass cartModel {get;set;} = new CartModelClass();
        public Cart cart { get; set; } = new Cart();
        public Cart cart2 { get; set; } = new Cart();
        public string logoutchecksession {get;set;} = "";
        public int customerid { get; set; } 
         public Products products { get; set; } = new Products();
        public async Task<IActionResult> OnGet(int productID)
        {
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                Console.WriteLine("customerID", customerid);
                cart2 = await _context.Cart.Where(c=>c.Customer_Id==customerid && c.Product_Id == productID).FirstOrDefaultAsync();
                ProductInfo = await _context.Products.FirstOrDefaultAsync(p=>p.Product_Id==productID);
                if(ProductInfo==null)throw new Exception("Did not get Products");
                 ProductReviewDetails = await (from review in _context.Reviews
                                              join account in _context.Account 
                                              on review.Customer_Id equals account.Account_Id
                                              join userDetails in _context.UserDetails 
                                              on account.Account_Id equals userDetails.Accounts_Id
                                              where review.Product_Id == productID
                                              select new UserReviewDetails
                                              {
                                                  UserName = userDetails.UserName,
                                                  ReviewId = review.Review_Id,
                                                  Ratings = review.Ratings,
                                                  ReviewDescription = review.Description,
                                                  ProductId = review.Product_Id
                                              }).ToListAsync();
        

                if (ProductReviewDetails.Count<0)
                    throw new Exception("Review not available for this product");
                return Page();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }   
        public async Task<IActionResult> OnPostAddCartAndBuy(int prodId){
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession == null)return RedirectToPage("../User/UserLogin");
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);

                if(cart!=null){
                    products = await _context.Products.FirstOrDefaultAsync(p=>p.Product_Id==prodId);
                    if(products.Quantity<=cart.Quantity){
                        TempData["datamsg"] = "Maximum Products Available to you";
                        return Redirect("~/User/Productanddetails?productID=" + prodId);
                    }
                    cart.Quantity = cart.Quantity + 1;
                    await _context.SaveChangesAsync();
                    return RedirectToPage("../User/UserCart");
                }

                var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();

                return RedirectToPage("../User/UserCart");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }

        public async Task<IActionResult> OnPostAddToCart(int prodId){
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession == null)return RedirectToPage("../User/UserLogin");
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);

                if(cart!=null){
                    products = await _context.Products.FirstOrDefaultAsync(p=>p.Product_Id==prodId);
                    if(products.Quantity<=cart.Quantity){
                        TempData["datamsg"] = "Maximum Products Available to you";
                        return Redirect("~/User/Productanddetails?productID=" + prodId);
                    }
                    cart.Quantity = cart.Quantity + 1;
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/Productanddetails?productID=" + prodId);

                }
               var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();
                return Redirect("~/User/Productanddetails?productID=" + prodId);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }

        public async Task<IActionResult> OnPostDecreasefromCart(int prodId){
             try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(logoutchecksession == null)return RedirectToPage("../User/UserLogin");
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);
                
                if(cart.Quantity==1){
                    _context.Cart.Remove(cart);
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/Productanddetails?productID=" + prodId);
                }

                if(cart!=null){
                    cart.Quantity = cart.Quantity - 1;
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/Productanddetails?productID=" + prodId);

                }
               var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();
                return RedirectToPage("../User/Productanddetails");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }
    }

    public class UserReviewDetails
    {
        public string UserName { get; set; }
        public int ReviewId { get; set; }
        public float Ratings { get; set; }
        public string ReviewDescription { get; set; }
        public int ProductId { get; set; }
    }
}

EsyaCart/Pages/User/UserCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EsyaCart.Data.Context;
using EsyaCart.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EsyaCart.Pages.User
{
    public class UserCart : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UserCart> _logger;

        public UserCart(ILogger<UserCart> logger,AppDbContext Dbcontext)
        {
            _logger = logger;
            _context = Dbcontext;
        }

        public List<CustomerProductsInCart> cartdata{ get; set; } = new List<CustomerProductsInCart>();
        public Cart cart { get; set; } = new Cart();
        public Products products { get; set; } = new Products();
        public string logoutchecksession {get;set;} = "";
        public int customerid { get; set; } 

        public int setbtnlologin { get; set; } = 1;
        public async Task<IActionResult> OnGet()
        {
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                if(customerid==0 || customerid==null ||logoutchecksession==null){
                    setbtnlologin = 0;
                    return Page();
                }
                setbtnlologin=1;
                cartdata = await (from products in _context.Products
                join cart in _context.Cart
                on products.Product_Id equals cart.Product_Id
                where cart.Customer_Id==customerid
                select new CustomerProductsInCart
                {
                    ProductName = products.ProductName,
                    ProductImageUrl = products.ImageUrl,
                    ProductPrice = products.Price,
                    ProductQuantity = cart.Quantity,
                    Product_ID = cart.Product_Id
                }).ToListAsync();
                if(cartdata.Count<0)throw new Exception("Cart is Empty");
                return Page();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }

         public async Task<IActionResult> OnPostAddToCart(int prodId){
            try
            {
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);

                if(cart!=null){
                    products = await _context.Products.FirstOrDefaultAsync(p=>p.Product_Id==prodId);
                    if(products.Quantity<=cart.Quantity){
                        TempData["datamsg"] = "Maximum Products Available To You";
                        return Redirect("~/User/UserCart");
                    }
                    cart.Quantity = cart.Quantity + 1;
                        await _context.SaveChangesAsync();
                        return Redirect("~/User/UserCart");
                }
               var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();
                return Redirect("~/User/UserCart");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }

        public async Task<IActionResult> OnPostDecreasefromCart(int prodId){
             try
            {
                Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
                Response.Headers["Pragma"] = "no-cache";
                Response.Headers["Expires"] = "0";
                logoutchecksession = HttpContext.Session.GetString("UserSessionId");
                customerid = HttpContext.Session.GetInt32("CustomerId")??0;
                cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);
                
                if(cart.Quantity==1){
                    _context.Cart.Remove(cart);
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/UserCart");
                }

                if(cart!=null){
                    cart.Quantity = cart.Quantity - 1;
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/UserCart");

                }
               var newcartModel = new Cart(){
                    Customer_Id = customerid,
                    Product_Id = prodId,
                    Quantity = 1
                };

                await _context.Cart.AddAsync(newcartModel);
                await _context.SaveChangesAsync();
                // return RedirectToPage("~/User/UserCart");
                return Page();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Page();
            }
        }

        public async Task<IActionResult> OnPostRemovefromCart(int prodId){
           try
           {
             cart = await _context.Cart.FirstOrDefaultAsync(p=>p.Product_Id == prodId);
                
                    _context.Cart.Remove(cart);
                    await _context.SaveChangesAsync();
                    return Redirect("~/User/UserCart");
           }
           catch (Exception e)
           {
            Console.WriteLine(e.Message);
             return Redirect("~/User/UserCart");
           }
        }
    }
    public class CustomerProductsInCart
    {
        public string ProductName { get; set; }
        public string ProductImageUrl {get; set; }


        public double ProductPrice { get; set; }
        public int ProductQuantity {get;set;}
        public int Product_ID {get;set;}
    }
}

EsyaCart/Pages/User/Productanddetails.cshtml
@page
@model EsyaCart.Pages.User.Productanddetails
@using System.Globalization
@{
    ViewData["Title"] = "Productanddetails";
}


<div class="container">
    @if(TempData["datamsg"]!=null)
    {
        <div class="text-danger fs-4 text-center">
        @TempData["datamsg"]
        </div>
    }
    <div class="container-main">
        <div class="image-container">
            <img src="~/Uploads/@Model.ProductInfo.ImageUrl" alt="" class="img border border-2 p-4">
        </div>
        <form method="post" class="buybtn-container">
            <button type="submit" asp-page-handler="AddCartAndBuy" asp-route-prodId="@Model.ProductInfo.Product_Id" class="form-control buybtn fs-3"><i class="fa-solid fa-bag-shopping fs-4" style="color: #ffffff;"></i> Buy</button>
        </form>
        @if(Model.cart2==null){
            <form method="post" class="cartbtncontainer">
                <button type="submit" asp-page-handler="AddToCart" asp-route-prodId="@Model.ProductInfo.Product_Id" class="form-control addcartbtn fs-3"><i class="fa-solid fa-cart-shopping fs-4" style="color: #ffffff;"></i> Add to cart </button>
            </form>
        }else{
            <div class="d-flex justify-content-center align-items-center cartbtncontainer2">
                <form method="post" class="ms-2">
                    <button type="submit" asp-page-handler="DecreasefromCart" asp-route-prodId="@Model.ProductInfo.Product_Id" class="btn btn-danger fs-3 px-3">-</button>
                </form>
                <h2 class="text-center mx-3">@Model.cart2.Quantity.ToString()</h2>
                <form method="post" class="me-2">
                    <button type="submit" asp-page-handler="AddToCart" asp-route-prodId="@Model.ProductInfo.Product_Id" class="btn btn-primary fs-3">+</button>
                </form>
                
            </div>
        }
        <div class="detailsContainer">
                    <div class="">                
                        <div class="" >
                            <h3  style="color: #495057;">@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Model.ProductInfo.ProductName.ToLower())</h3>
                            <p class="fs-4" style="font-weight: 500; color: #495057;">₹ @Model.ProductInfo.Price</p>
                        </div>

                        <div class="">
                            <h3 class=""  style="color: #495057;">Product Description</h3>
                            <p class="fs-5" style="color: #495057;">@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Model.ProductInfo.Description.ToLower())</p> 
                        </div> 
                    </div>

                <div class="border border-1 border-dark p-4" style="color: #495057;">
                    <h2 class="reviewstext" style="color: #495057;">Reviews & Rating</h2>
                    @if(Model.ProductReviewDetails.Count>0){
                            @foreach(var review in Model.ProductReviewDetails){
                        <div class="">
                            <p>@review.UserName</p>
                            <div class="text-white d-flex" style="width: max-content;">
                                
                                @{
                                    int integerPart=0;
                                    double decimalPart=0;
                                    integerPart = (int)Math.Truncate(review.Ratings); 
                                    decimalPart = review.Ratings - integerPart;
                                    if(integerPart>0){
                                        for(int i=0;i<integerPart;i++){
                                            <p class="px-1 fs-6"><i class="fa-solid fa-star" style="color:#ffc800;"></i></p>
                                        }
                                    }
                                    if(decimalPart>0){
                                        <p class="px-1 fs-6"><i class="fa-solid fa-star-half" style="color:#ffc800;"></i></p>
                                    }
                                }
                            </div>
                            <p class="fs-5 textcolor">@review.ReviewDescription</p>
                            
                        </div>
                        }
                    }else{
                        <h3 class="textcolor">No Reviews</h3>
                    }
                </div>
            
        </div>
    </div>
</div>

EsyaCart/Pages/User/SearchBar.cshtml
@page
@model EsyaCart.Pages.User.SearchBar
@{
    Layout=null;
}

EsyaCart/Pages/User/UserCart.cshtml
@page
@model EsyaCart.Pages.User.UserCart
@{
    double totalsum = 0;
}
@if(TempData["datamsg"]!=null)
{
    <div class="fs-5 text-danger text-center">
    @TempData["datamsg"] 
    </div>
}

<div class="w-100 d-flex justify-content-center">
    @if(Model.setbtnlologin==1){
    <div class="table-responsive w-100 ms-5">
    @if(Model.cartdata.Count > 0)
    {
        <div class="">
            <p class="fs-1 text-center mb-5" style="color: #495057;">Your Cart</p>
        </div>
        double sum = 0;
        <table class="w-100 table table-striped">

            <thead class="border-top-0 border-end-0 border-start-0 border-dark border-2">
                <tr class="my-5">
                    <th class="text-center" style="color: #495057;">Product</th>
                    <th class="text-center" style="color: #495057;">Product Name</th>
                    <th class="text-center" style="color: #495057;">Product Quantity</th>
                    <th class="text-center" style="color: #495057;"></th>
                    <th class="text-center" style="color: #495057;"></th>
                    <th class="text-center" style="color: #495057;">Price</th>
                </tr>
            </thead>
              
        @foreach(var cartdata in Model.cartdata){
            <tbody style="border-spacing: 0 10px; background-color: #ffffff !important;">
                <tr class="border-top-0 border-end-0 border-start-0 border-top-0 border-dark border-1 table-row-spacing">
                    <td class="text-center cart-cell" style="color: #495057;">
                        <img src="~/Uploads/@cartdata.ProductImageUrl" alt="" width="100px" height="100px">
                    </td>
                    <td class="text-center cart-cell fs-4" style="color: #495057;">@cartdata.ProductName</td>
                    <td class="text-center cart-cell fs-4" style="color: #495057;">@cartdata.ProductQuantity</td>
                    <td class="text-center cart-cell fs-4" style="color: #495057;">
                        
                            <div class="d-flex justify-content-center align-items-center cartbtncontainer2">
                                <form method="post" class="ms-2">
                                    <button type="submit" asp-page-handler="DecreasefromCart" asp-route-prodId="@cartdata.Product_ID" class="btn btn-danger fs-5 px-3">-</button>
                                </form>
                                <h2 class="text-center mx-3">@cartdata.ProductQuantity.ToString()</h2>
                                <form method="post" class="me-2">
                                    <button type="submit" asp-page-handler="AddToCart" asp-route-prodId="@cartdata.Product_ID" class="btn btn-primary fs-5">+</button>
                                </form>
                            </div>
                            <td>
                                <form method="post" class="me-2">
                                    <button type="submit" asp-page-handler="RemovefromCart" asp-route-prodId="@cartdata.Product_ID" class="btn btn-danger fs-5"><i class="fa-regular fa-trash-can"></i></button>
                                </form>
                            </td>
                        </td>
                        <td class="text-center cart-cell fs-4" style="color: #008728;">₹ @(cartdata.ProductPrice * cartdata.ProductQuantity)</td>
                        <p style="display: none;">@(sum += (cartdata.ProductPrice * cartdata.ProductQuantity)) @(totalsum = sum)</p>
                    </tr>
                </tbody>
            }

            <div class="carttotal">
                <button class="btn form-control btncolor btn-secondary" data-bs-toggle="modal" data-bs-target="#cartModal">
                    <span class="mx-3 fs-3">Your Total:₹ @sum</span><span class="mx-3 fs-3">Checkout</span>
                </button>
            </div>
        </table>
    }
    else
    {
        <div style="color: #56595b; display: flex;align-items: center; justify-content: center; height:100vh">
            <div class="">
                <h1><i class="fa-solid fa-cart-shopping fs-4 m-3"></i> Your Cart Is Empty</h1>
                <div class="btn btn-secondary py-2 px-4" style="display: flex;align-items: center; justify-content: center;">
                <a asp-page="../User/Dashboard" class="text-decoration-none text-white">Go To Shopping</a>
                </div>
            </div>
        </div>
        
    }
</div>

<!-- Modal -->
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cartModalLabel">Your Cart Summary</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="w-100 table table-striped">
                    <thead class="border-top-0 border-end-0 border-start-0 border-dark border-2">
                        <tr class="my-5">
                            <th class="text-center">Product</th>
                            <th class="text-center">Product Name</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var cartdata in Model.cartdata)
                        {
                            <tr>
                                <td class="text-center">
                                    <img src="~/Images/User/Logo.jpeg" alt="Product Image" width="30px" height="30px">
                                </td>
                                <td class="text-center">@cartdata.ProductName</td>
                                <td class="text-center">@cartdata.ProductQuantity</td>
                                <td class="text-center">@(cartdata.ProductPrice * cartdata.ProductQuantity)</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <h4 class="text-end">Total: @totalsum</h4>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a asp-page="../User/UserOrders" asp-route-TotalPrice="@totalsum" class="btn btn-primary">Proceed to Payment</a>
            </div>
        </div>
    </div>
</div>
}else if(Model.setbtnlologin==0){
    <div class="stylecartemptydiv">
        <div class="d-flex flex-column  align-items-center justify-content-center">
            <i class="fa-solid fa-cart-shopping fs-4 m-3"></i>
            <p class="fs-4 m-3">Your Cart Is Empty</p>
        </div>
        <div class="">
            <div class="btn btn-secondary py-2 px-4">
            <a asp-page="../User/Dashboard" class="text-decoration-none text-white">Go To Shopping</a>
            </div>
            <div class="btn btn-danger py-2 px-4">
                <a asp-page="../User/UserLogin" class="text-decoration-none text-white">Go To Login</a>
            </div>
        </div>
    </div>
}

</div>

EsyaCart/Pages/User/UserLogout.cshtml
@page
@model EsyaCart.Pages.User.UserLogout
@{
    Layout=null;
}

EsyaCart/Pages/User/UserOrders.cshtml
@page
@model EsyaCart.Pages.User.UserOrders
@{
    Layout = null;
}

    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/user.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EsyaCart.styles.css" asp-append-version="true"/>

@if(TempData["Data"]!=null)
{
    <div class="containermainupper">
        <div class="containermain">
            <div class="payment">
                <p class="fs-1 text-center" style="color:rgba(89, 188, 89, 0.763);">Payment Successfull</p>
                <p class="fs-1 text-center border-circle">✓ </p>
            </div>
            <div class="paydetails">
                <b><p class="fs-5">ThankYou! Your Payment of Rs @TempData["Data"] has been recieved</p></b>
            </div>
            <div class="btns btn">
                <a asp-page="../User/Dashboard" class="text-decoration-none fs-4 text-white">Ok</a>
            </div>
        </div>
    </div>
}